//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidId { get; set; }
        public int Item { get; set; }
        public int Buyer { get; set; }
        public int Price { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Buyer Buyer1 { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
